### ISSUE TITLE
Add support for PHP 8.0 and drop support for PHP 7.2

### ISSUE THREAD

**Issue by rieschl** [doctrine/DoctrineMongoODMModule#227]
Do we want to drop support for PHP 7.2?
Security support ends in about a month.
Are there some Doctrine guidelines about supported PHP versions?

In addition, PHP8 will be released soon. The MongoDB PHP driver [doesn't support PHP 8](https://github.com/mongodb/mongo-php-driver/issues/1161), yet, but according to @alcaeus a (beta) version will be released, soon.

**Comment by malarzm** [comment]
I think that modules/bundles should support the same PHP version as a library they are integrating.

**Comment by rieschl** [comment]
> 
> 
> I think that modules/bundles should support the same PHP version as a library they are integrating.

Okay, so staying at 7.2. Then just PHP 8 support _additionally_?

**Comment by TomHAnderson** [comment]
Don't add PHP 8 support until the mongodb driver is out of beta.  Dropping 7.2 support for the sake of not supporting it isn't a necessity.  I prefer to migrate support forward as requirements dictate.

**Comment by NiMeDia** [comment]
Are there any news on this? AFAIK the driver is out of beta and the other doctrine libs do support ^8.0 now.

**Comment by driehle** [comment]
Version [1.9.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.9.0) should be a stable release supporting PHP 8.0. If anyone is willing to provide a PR dropping PHP 7.2, I'll happily review it.

**Comment by rieschl** [comment]
> Version [1.9.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.9.0) should be a stable release supporting PHP 8.0. If anyone is willing to provide a PR dropping PHP 7.2, I'll happily review it.

IMO dropping 7.2 probably is not necessary, but adding support for PHP 8 would be nice.
I'll try to get to it in November (after Hacktoberfest ^^).

**Comment by driehle** [comment]
We have already dropped PHP 7.2 in doctrine-laminas-hydrator 2.2 and I'll drop PHP 7.2 in DoctrineModule with the next minor. The reason behind is that Laminas has already began dropping PHP 7.2 in most components a couple of months ago. Since this is supposed to be an integration with Laminas, it doesn't make sense to continue supporting PHP 7.2 here, if it is not supported upstream anymore. So feel free to drop PHP 7.2. :-)

**Comment by driehle** [comment]
A few notes on what needs to be done:

- in `.github/workflows/coding-standards.yml`: php-version needs to be changed to 8.0
- in `phpcs.xml.dist`: minimal PHP version needs to be changed to 70300
- in `.github/workflows/continoues-integration.yml`: need to add 8.0 and remove 7.2, change lowest dependencies test to 7.3

Raising the minimum PHP version for PHPCs may raise new issues by not needing to support 7.2 anymore. These need to be fixed if they are no BC breaks and suppressed otherwise.

Further, PHPUnit needs to be updated from 8.5 to 9.5, as 8.5 does not support PHP 8.0. This will likely throw deprecation messages on `prophesize()` which can be solved by adding `phpspec/prophecy-phpunit` to dev requirements. [fca5b3](https://github.com/doctrine/DoctrineModule/pull/738/commits/fca5b369f40a0b95c7514be2901768eab1ce6f9e) in  https://github.com/doctrine/DoctrineModule/pull/738 can possibly provide some directions.

**Comment by driehle** [comment]
Support for PHP 8.1 (#249, #253) is now released with 4.0.0.

**Comment by rieschl** [comment]
> Support for PHP 8.1 (#249, #253) is now released with 4.0.0.

thank you very much!
